from biogeme.expressions import *
pass_ID=Variable('pass_ID')
scenario=Variable('scenario')
time_crit=Variable('time_crit')
JRT=Variable('JRT')
WT=Variable('WT')
commuter=Variable('commuter')
age_50_65=Variable('age_50_65')
age_65plus=Variable('age_65plus')
Crowding_3_2=Variable('Crowding_3_2')
Crowding_4_3=Variable('Crowding_4_3')
Crowding_4_2=Variable('Crowding_4_2')
output_choice=Variable('output_choice')
_biogroups=Variable('_biogroups')
